// !LOCNS:galactic_war
define([
    'shared/gw_tutorial_p4'
], function(
    planets4
) {
    return {
        "name": "!LOC:Interplanetary Warfare",
        "coordinates":[ -0.3, 0.25, 0.1],
        "biome":"tropical",
        "distance":1,
        "explored": true,
        "hasCard": false,
        "cardList": [],
        "history":[],
        "ai": {
            "commander": {
                "ObjectName": "TankAeson",
                "UnitSpec": "/pa/units/commanders/tutorial_ai_commander_3/tutorial_ai_commander_3.json",
            },
            "econ_rate": 0.5,
            "color": [
                [236, 34, 35],
                [192, 192, 192]
            ],
            "team": 2,
            "name": "Target",
            "personality": {
                "percent_land": 1.0,
                "percent_air": 0.00,
                "percent_naval": 0.00,
                "percent_orbital": 0.00,
                "metal_drain_check": 0.24,
                "energy_drain_check": 0.25,
                "metal_demand_check": 0.41,
                "energy_demand_check": 0.50,
                "micro_type": 0,
                "go_for_the_kill": false,
                "neural_data_mod": 2.0,
                "personality_tags": [
                    "Tutorial",
                    "SlowerExpansion"
                ],
                "priority_scout_metal_spots": false,
                "factory_build_delay_min": 60,
                "factory_build_delay_max": 120,
                "min_basic_fabbers": 1,
                "max_basic_fabbers": 1,
                "fabber_to_factory_ratio_basic": 1.5,
                "fabber_to_factory_ratio_advanced": 1.0,
                "fabber_alone_on_planet_mod": 2.0,
                "min_advanced_fabbers": 1,
                "max_advanced_fabbers": 1,
                "basic_to_advanced_factory_ratio": 0,
                "adv_eco_mod": 100.0,
                "adv_eco_mod_alone": 100.0,
                "unable_to_expand_delay": 12000,
                "per_expansion_delay": 60000,
                "enable_commander_danger_responses": false
            },
            "faction": 2
        },
        "system": {
            "name": "!LOC:Interplanetary Warfare",
            "isRandomlyGenerated": true,
            "description": [
                "<div class='figure_wrapper'>",
                "   <img src='coui://ui/main/game/guide/article/img/img_mouse_lclick.png'/>",
                "   <div class='text'>", "!LOC:[strong]JUMP[/strong] to this star system.", "</div>",
                "</div>",
                "<div class='figure_wrapper'>",
                "   <img src='coui://ui/main/game/guide/article/img/img_mouse_lclick.png'/>",
                "   <div class='text'>", "!LOC:[strong]FIGHT[/strong] the enemy commander.", "</div>",
                "</div>"
            ],
            "players":[0,2],
            "planets": planets4,
            "tutorial": [
                {
                    "title": "!LOC:Annihilate the Enemy",
                    "body": [
                        "<span>",
                        "<div class='figure_wrapper'>",
                        "   <img src='coui://ui/main/game/guide/article/img/commander_x.png'/>",
                        "   <div class='text'>", "!LOC:The enemy commander has landed on the ice planet.",
                        "   <br>", "<br>", "!LOC:[strong]Annihilate[/strong] the enemy commander by smashing it with a planet.", "</div>",
                        "</div>",
                        "</span>"
                    ],
                    "audio": "/VO/Computer/Tutorial/Tutorial_4/0",
                    "delaySeconds": 9
                },
                {
                    "title": "!LOC:Orbital",
                    "body": [
                        "<span>",
                        "<div class='figure_wrapper'>",
                        "    <img class='visual' src='coui://ui/main/game/guide/article/img/img_mouse_lclick.png'/>",
                        "    <div class='text'>", "!LOC:[style=control]Select landing zone 1 on the Tropical Planet 'Annihilation'[/style] and start the annihilation.", "</div>",
                        "</div>",
                        "!LOC:Orbital units are expensive units that fly in low planet orbit, can traverse between planets, but are vulnerable to anti-orbital weaponry.",
                        "<br>",
                        "<br>",
                        "<div class='figure_wrapper'>",
                        "   <img class='visual' src='coui://ui/main/game/guide/article/img/vehicle_factory.png'/>",
                        "   <img class='visual' src='coui://ui/main/game/guide/article/img/fabrication_vehicle.png'/>",
                        "   <div class='text'>", "!LOC:[style=control]Build a factory and several fabrication units.[/style]", "</div>",
                        "</div>",
                        "<br>",
                        "<br>",
                        "<div class='figure_wrapper'>",
                        "    <img class='visual' src='coui://ui/main/game/guide/article/img/orbital_launcher.png'/>",
                        "    <div class='text'>", "!LOC:[style=control]Build an orbital launcher with the fabrication unit.[/style]", "</div>",
                        "</div>",
                        "!LOC:[strong]Note:[/strong] Commanders supply enough metal and energy to build a factory before building metal extractors and energy plants.",
                        "</span>",
                    ],
                    "audio": "/VO/Computer/Tutorial/Tutorial_4/1"
                },
                {
                    "title": "!LOC:Area Patrol",
                    "body": [
                        "<span>",
                        "!LOC:Most unit orders can be given as an area command.",
                        "<br>",
                        "<div class='figure_wrapper'>",
                        "    <img class='visual' src='coui://ui/main/game/guide/article/img/icons_command_patrol.png'/>",
                        "    <div class='text'>", "!LOC:[style=control]Select a unit and left click the patrol icon[/style], or press [style=control]P[/style].", "</div>",
                        "</div>",
                        "<div class='figure_wrapper'>",
                        "    <img class='visual' src='coui://ui/main/game/guide/article/img/img_mouse_lclick.png'/>",
                        "    <div class='text'>", "!LOC:[style=control]Left click and drag[/style] a circle around an area to issue an area patrol.", "</div>",
                        "</div>",
                        "<br>",
                        "!LOC:Combat units will patrol the area and engage enemies.",
                        "<br>",
                        "<br>",
                        "!LOC:Fabrication units will assist factories and other fabbers in the area.",
                    ],
                    "audio": "/VO/Computer/Tutorial/Tutorial_4/2"
                },
                {
                    "title": "!LOC:Area Reclaim",
                    "body": [
                        "<span>",
                        "<div class='figure_wrapper'>",
                        "    <img class='visual' src='coui://ui/main/game/guide/article/img/fabrication_vehicle.png'/>",
                        "    <div class='text'>", "!LOC:[style=control]Select another fabrication unit.[/style]", "</div>",
                        "</div>",
                        "<br>",
                        "<div class='figure_wrapper'>",
                        "    <img class='visual' src='coui://ui/main/game/guide/article/img/reclaim_icon.png'/>",
                        "    <div class='text'>", "!LOC:[style=control]Left click on the reclaim icon[/style] or press [style=control]E[/style].", "</div>",
                        "</div>",
                        "<br>",
                        "<div class='figure_wrapper'>",
                        "    <img class='visual' src='coui://ui/main/game/guide/article/img/reclaim_icon.png'/>",
                        "    <div class='text'>", "!LOC:[style=control]Left click and drag[/style] a circle around an area to reclaim wreckage and trees for metal.", "</div>",
                        "</div>",
                        "</span>",
                    ],
                    "audio": "/VO/Computer/Tutorial/Tutorial_4/3"
                },
                {
                    "title": "!LOC:Naval Units",
                    "body": [
                        "<span>",
                        "<div class='figure_wrapper'>",
                        "   <img class='visual' src='coui://ui/main/game/guide/article/img/battleship_icon.png'/>",
                        "   <div class='text'>", "!LOC:[strong]Naval:[/strong] Very heavily armored units but are relegated to water movement.", "</div>",
                        "</div>",
                        "<br>",
                        "<div class='figure_wrapper'>",
                        "   <img class='visual' src='coui://ui/main/game/guide/article/img/naval_factory.png'/>",
                        "   <div class='text'>", "!LOC:Naval units are built from the naval factory.", "</div>",
                        "</div>",
                        "<br>",
                        "<br>",
                        "!LOC:Many structures can be built on top of the water surface.",
                        "<br>",
                        "<br>",
                        "!LOC:Units and structures that fire torpedoes can target submarines under water and units on the seafloor.",
                        "</span>",
                    ],
                    "audio": "/VO/Computer/Tutorial/Tutorial_4/4"
                },
                {
                    "title": "!LOC:Orbital Movement",
                    "body": [
                        "<span>",
                        "<div class='figure_wrapper'>",
                        "   <img class='visual' src='coui://ui/main/game/guide/article/img/vehicle_factory_adv_icon.png'/>",
                        "   <img class='visual' src='coui://ui/main/game/guide/article/img/bot_factory_adv_icon.png'/>",
                        "   <img class='visual' src='coui://ui/main/game/guide/article/img/fabrication_vehicle_adv_icon.png'/>",
                        "   <img class='visual' src='coui://ui/main/game/guide/article/img/fabrication_bot_adv_icon.png'/>",
                        "</div>",
                        "<br>",
                        "!LOC:[style=control]Build an advanced factory and an advanced fabrication unit.[/style]",
                        "</div>",
                        "<br>",
                        "<div class='figure_wrapper'>",
                        "   <img class='visual' src='coui://ui/main/game/guide/article/img/orbital_lander_icon.png'/>",
                        "    <div class='text'>", "!LOC:[style=control]Build an Astraeus[/style] from the orbital launcher.", "</div>",
                        "</div>",
                        "<div class='figure_wrapper'>",
                        "   <img class='visual' src='coui://ui/main/game/guide/article/img/icons_command_load.png'/>",
                        "    <div class='text'>", "!LOC:[style=control]Load the advanced fabrication unit onto the Astraeus.[/style]", "</div>",
                        "</div>",
                        "<div class='figure_wrapper'>",
                        "    <img class='visual' src='coui://ui/main/game/guide/article/img/img_mouse_scroll_45.png'/>",
                        "    <div class='text'>", "!LOC:[style=control]Zoom out to the star system view[/style] and [style=control]zoom in on the moon.[/style]", "</div>",
                        "</div>",
                        "<div class='figure_wrapper'>",
                        "   <img class='visual' src='coui://ui/main/game/guide/article/img/icons_command_unload.png'/>",
                        "    <div class='text'>", "!LOC:[style=control]Issue an unload command to the Astraeus[/style] on the surface of the moon.", "</div>",
                        "</div>",
                        "</span>",
                    ],
                    "audio": "/VO/Computer/Tutorial/Tutorial_4/5",
                    "delaySeconds": 7
                },
                {
                    "title": "!LOC:Camera Management",
                    "body": [
                        "<span>",
                        "<div class='figure_wrapper'>",
                        "   <img class='visual' src='coui://ui/main/game/guide/article/img/icon_camera.png'/>",
                        "    <div class='text'>", "    ", "!LOC:[style=control]Press shift + 1[/style] to save a camera anchor.", "</div>",
                        "</div>",
                        "<br>",
                        "<div class='figure_wrapper'>",
                        "   <img class='visual' src='coui://ui/main/game/guide/article/img/icon_camera.png'/>",
                        "    <div class='text'>", "    ", "!LOC:[style=control]Press alt + 1[/style] to return your camera to the saved anchor spot.", "</div>",
                        "</div>",
                        "<br>",
                        "!LOC:You can save up to 10 camera anchors by using numbers 0 - 9.",
                        "</span>",
                    ],
                    "audio": "/VO/Computer/Tutorial/Tutorial_4/6"
                },
                {
                     "title": "!LOC:Planetary Expansion",
                     "body": [
                        "<span>",
                        "<div class='figure_wrapper'>",
                        "   <img class='visual' src='coui://ui/main/game/guide/article/img/teleporter_icon.png'/>",
                        "   <div class='text'>", "!LOC:[style=control]Build a teleporter[/style] on the moon with your advanced fabrication unit.", "</div>",
                        "</div>",
                        "<br>",
                        "<div class='figure_wrapper'>",
                        "   <img class='visual' src='coui://ui/main/game/guide/article/img/teleporter_icon.png'/>",
                        "   <div class='text'>", "!LOC:[style=control]Build a second teleporter[/style] on the earth-like planet with the commander or a fabrication unit.", "</div>",
                        "</div>",
                        "<br>",
                        "<div class='figure_wrapper'>",
                        "   <img class='visual' src='coui://ui/main/game/guide/article/img/link_icon.png'/>",
                        "   <div class='text'>", "!LOC:[style=control]Connect the teleporters[/style] by selecting one and [style=control]right click[/style] on the second one.", "</div>",
                        "</div>",
                        "<br>",
                        "!LOC:Teleporters require energy to remain active.",
                        "<br>",
                        "<br>",
                        "<div class='figure_wrapper'>",
                        "   <img class='visual' src='coui://ui/main/game/guide/article/img/fabrication_vehicle_adv_icon.png'/>",
                        "   <img class='visual' src='coui://ui/main/game/guide/article/img/fabrication_bot_adv_icon.png'/>",
                        "</div>",
                        "!LOC:[style=control]Build many more advanced fabrication units and send them through the teleporter to the moon.[/style]",
                        "</span>",
                     ],
                    "audio": "/VO/Computer/Tutorial/Tutorial_4/7"
                },
                {
                    "title": "!LOC:Halley Engines",
                    "body": [
                        "<span>",
                        "<div class='figure_wrapper'>",
                        "   <img class='visual' src='coui://ui/main/game/guide/article/img/delta_v_engine_icon.png'/>",
                        "   <div class='text'>", "!LOC:[style=control]Build a Halley Engine[/style] on the moon using all the advanced fabrication units.", "</div>",
                        "</div>",
                        "<br>",
                        "!LOC:When the notification for the Halley Engine arrives, [style=control]left click on the orange notification and select the ice planet for annihilation.[/style]",
                        "<br>",
                        "<br>",
                        "<div class='figure_wrapper'>",
                        "   <img class='visual' src='coui://ui/main/shared/img/planets/earth.png'/>",
                        "   <div class='text'>[style=control]Nail[/style]</div>",
                        "</div>",
                        "<br>",
                        "!LOC:[style=control]Zoom in on the ice planet to watch the annihilation.[/style]",
                        "</span>",
                    ],
                    "audio": "/VO/Computer/Tutorial/Tutorial_4/8"
                },
                {
                    "title": "!LOC:Commander Quotes",
                    "body": [
                        "<span>",
                        "<i>",
                        "<div class='text'>", '!LOC:"There is no anti-asteroid."', "</div>",
                        "<br>",
                        "<div class='text'>", '!LOC:"Orbital is death-from-above for the death-from-above units."', "</div>",
                        "<br>",
                        "<div class='text'>", '!LOC:"Single point orders are for sub-commanders. Real commanders use area commands."', "</div>",
                        "<br>",
                        "<div class='text'>", '!LOC:"Commanders in orbit are either dead or dying."', "</div>",
                        "</i>",
                        "</span>",
                    ],
                    "audio": "/VO/Computer/Tutorial/Tutorial_4/9"
                }
            ],
        }
    }
});
